options:
  check-dns:
    default: ""
    type: string
    description: |
      A space-separated list of DNS names to check.  If any of the names are not resolvable, alert as CRITICAL.
  check-rally:
    default: False
    type: boolean
    description: |
      Switch to turn on or off rally checks via the fcbtest snap. By default, rally nrpe check is disabled.
  skip-rally:
    default: ""
    type: string
    description: |
      Comma separated list of OpenStack components to not monitor. An empty string means all components will be
      monitored (up to the number of currently supported components: Cinder, Glance, Nova, Neutron).
      Sample: skip-rally=cinder
  os-credentials:
    default: ""
    type: string
    description: |
      Comma separated OpenStack credentials to be used by nagios.
      It is strongly recommended this be a user with a dedicated role,
      and not a full admin.  Takes the format of
      username=foo, password=bar, credentials_project=baz, region_name=Region1, auth_url=http://127.0.0.1:35357
  nova_warn:
    default: 2
    type: int
    description: |
      Warning level for nova aggregate unit count check - setting this to -1 will effectively disable host aggregate checks.
  nova_crit:
    default: 1
    type: int
    description: |
      Critical level for nova aggregate unit count check - setting this to -1 will effectively disable host aggregate checks.
  skipped_host_aggregates:
    type: string
    default: ""
    description: |
      Comma separated list of host aggregates that need to be skipped from checks. Example "Agg1,AGg2" or 'Aggregate3'.
      This is a case-insensitive option.
  nagios_context:
    default: "juju"
    type: string
    description: |
      Used by the nrpe subordinate charms.
      A string that will be prepended to instance name to set the host name
      in nagios. So for instance the hostname would be something like:
          juju-myservice-0
      If you're running multiple environments with the same services in them
      this allows you to differentiate between them.
  nagios_servicegroups:
    default: ""
    type: string
    description: |
      A comma-separated list of nagios servicegroups.
      If left empty, the nagios_context will be used as the servicegroup
  trusted_ssl_ca:
    type: string
    default: ''
    description: |
      base64 encoded SSL ca cert to use for OpenStack API client connections.
  skip-disabled:
    type: boolean
    default: false
    description: |
      An option to specify whether you want Warning alerts in nagios for disabled nova-compute hosts.
  tls_warn_days:
    type: int
    default: 30
    description: |
      Number of days left for the TLS certificate to expire before warning.
  tls_crit_days:
    type: int
    default: 14
    description: |
      Number of days left for the TLS certificate to expire before alerting Critical.
  check_public_urls:
    type: boolean
    default: True
    description: |
      If true, create NRPE checks matching all 'public' URLs in the Keystone catalog.
  check_internal_urls:
    type: boolean
    default: True
    description: |
      If true, create NRPE checks matching all 'internal' URLs in the Keystone catalog.
  check_admin_urls:
    type: boolean
    default: True
    description: |
      If true, create NRPE checks matching all 'admin' URLs in the Keystone catalog.
  swift_check_params:
    type: string
    default: "/"
    description: |
      URL to use with check_http if there is a Swift endpoint.  Default is '/', but it's possible to add extra params,
      e.g. '/v3 -e Unauthorized -d x-openstack-request-id' or a different url, e.g. '/healthcheck'.  Mitaka Swift
      typically needs '/healthcheck'.
